# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"

  config.vm.network :forwarded_port, guest: 5432, host: 5433

  config.vm.synced_folder "../src", "/vagrant/pslib"

  config.vm.provision :shell, path: "postgres.install.sh"
  config.vm.provision :shell, path: "configure.sh"
end
